version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./:/app
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
        depends_on:
            - php
            - mysqldb

    php:
        image: php:fpm
        volumes:
            - ./:/app
        networks:
            - code-network

    composer:
        image: composer/composer:2.2.5
        restart: 'no'
        command: install
        volumes:
            - ./:/app


    mysqldb:
        image: mysql
        container_name: ${MYSQL_HOST}
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_ROOT_HOST=192.168.0.48/255.255.255.248
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        restart: 'always'
        expose:
            - '8989'
        ports:
            - "8989:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
        networks:
            network:
                ipv4_address: 172.20.0.2

    cache:
        image: redis:6.2-alpine
        restart: always
        ports:
            - '6379:6379'
        command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
        volumes: 
        volumes:
            - "./data/cache:/app/data"

    mailhog:
       image: mailhog/mailhog
       logging:
          driver: 'none'  # disable saving logs
       ports:
          - 1025:1025 # smtp server
          - 8025:8025 # web ui
       networks:
          - code-network
 
networks:
    network:
        ipam:
            config:
                - subnet: 172.20.0.0/16
    code-network:
        driver: bridge

